MODEL:
  PRETRAIN_PATH_T: '/data/object/pretrain_model/ViT-B-16.pt'
  TRANSFORMER_TYPE: 'ViT-B-16'
#  PRETRAIN_PATH_T: '/data/object/pretrain_model/vit-base.pth'
#  TRANSFORMER_TYPE: 'vit_base_patch16_224'
  STRIDE_SIZE: [ 16, 16 ]
  SIE_CAMERA: True
  DIRECT: 1
  SIE_COE: 1.0
  ID_LOSS_WEIGHT: 0.25
  TRIPLET_LOSS_WEIGHT: 1.0
  GLOBAL_LOCAL: False
  ADA: True
  GEN: True

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 8
  NUM_WORKERS: 14

DATASETS:
  NAMES: ('RGBNT201')
  ROOT_DIR: '/data/object/'

SOLVER:
  BASE_LR: 0.00035
  WARMUP_ITERS: 10
  MAX_EPOCHS: 45
  OPTIMIZER_NAME: 'Adam'
  IMS_PER_BATCH: 64
  EVAL_PERIOD: 1

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  MISS: "nothing"
#  MISS: "r"
#  MISS: "n"
#  MISS: "t"
#  MISS: "rn"
#  MISS: "rt"
#  MISS: "nt"

OUTPUT_DIR: '/data/object/Out_MFRNet/RGBNT201/'


